# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PA_Workspace/FPGA_project/common_project/vivado_examples/aes128_verilog/aes128_verilog.cache/wt [current_project]
set_property parent.project_path D:/PA_Workspace/FPGA_project/common_project/vivado_examples/aes128_verilog/aes128_verilog.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property include_dirs D:/PA_Workspace/FPGA_project/common_project/vivado_examples/aes128_verilog/aes128_verilog.srcs/sources_1/new [current_fileset]
read_verilog -library xil_defaultlib {
  D:/PA_Workspace/FPGA_project/common_project/cryptosrc/aes_googlevault/aes_sbox.v
  D:/PA_Workspace/FPGA_project/common_project/cryptosrc/aes_googlevault/aes_ks.v
  D:/PA_Workspace/FPGA_project/common_project/common/usb_module.v
  D:/PA_Workspace/FPGA_project/common_project/common/registers/registers.v
  D:/PA_Workspace/FPGA_project/common_project/cryptosrc/aes_googlevault/aes_core.v
  D:/PA_Workspace/FPGA_project/common_project/vivado_examples/aes128_verilog/aes128_verilog.srcs/sources_1/new/board.v
  D:/PA_Workspace/FPGA_project/common_project/common/cw305_top.v
}
read_vhdl -library xil_defaultlib C:/Users/Bob/Desktop/Random.vhdl
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/PA_Workspace/FPGA_project/common_project/common/cw305_main.xdc
set_property used_in_implementation false [get_files D:/PA_Workspace/FPGA_project/common_project/common/cw305_main.xdc]


synth_design -top cw305_top -part xc7a35tftg256-2


write_checkpoint -force -noxdef cw305_top.dcp

catch { report_utilization -file cw305_top_utilization_synth.rpt -pb cw305_top_utilization_synth.pb }
